Repository CS3219-AY2223S1/cs3219-project-ay2223s1-g8, pull requests merged in 2022-09, with the labels that each got.

#11 Fix user scripts and set environment variables
  user-service/.env sample
  user-service/.gitignore
  user-service/config/config.js
  user-service/model/database.js
  user-service/package.json
  user-service/test/test.js
Labels: UserService

#20 Frontend/socket
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/MatchTimer.css
  frontend/src/components/MatchTimer.js
  frontend/src/components/Timer.js
  frontend/src/views/MatchingPage.js
  testserver-service/.gitignore
  testserver-service/TestPage.js
  testserver-service/index.js
  testserver-service/package-lock.json
  testserver-service/package.json
Labels: Frontend

#24 Implemented landing page for frontend
  frontend/public/index.html
  frontend/src/.DS_Store
  frontend/src/App.js
  frontend/src/assets/logo-black.png
  frontend/src/assets/logo-black.svg
  frontend/src/assets/logo-colored.png
  frontend/src/assets/logo-white.png
  frontend/src/assets/pair-programming-animate.gif
  frontend/src/components/ChangePasswordModal/index.js
  frontend/src/components/DeleteAccountModal/index.js
  frontend/src/components/DeleteAccountModal/styles.scss
  frontend/src/components/NavBar/index.js
  frontend/src/components/NavBar/styles.scss
  frontend/src/scss/theme.scss
  frontend/src/views/LandingPage.js
  frontend/src/views/forgotPassword/ForgotPasswordPage.js
  frontend/src/views/landing/LandingPage.js
  frontend/src/views/landing/LandingPage.scss
  frontend/src/views/login/LoginPage.js
  frontend/src/views/login/LoginPage.scss
  frontend/src/views/signup/SignupPage.js
Labels: Frontend

#21 Update path for endpoints, add additional check username endpoint
  user-service/controller/user-controller.js
  user-service/index.js
  user-service/model/user-orm.js
  user-service/test/test.js
Labels: UserService

#31 Update userService endpoints in frontend
  frontend/src/components/NavBar/index.js
  frontend/src/routes/PrivateRoutes.js
  frontend/src/routes/PublicRoutes.js
  frontend/src/stores/user/user.actions.js
  frontend/src/stores/user/user.slice.js
  frontend/src/utils/authUtils.js
  frontend/src/utils/configs.js
  frontend/src/utils/localStorageUtils.js
  frontend/src/views/signup/SignupPage.js
Labels: Frontend

#22 Matching Service
  README.md
  frontend/package-lock.json
  frontend/public/index.html
  frontend/public/robots.txt
  frontend/src/components/MatchTimer.js
  matching-service/.env.sample
  matching-service/.eslintrc.json
  matching-service/.gitignore
  matching-service/config/index.js
  matching-service/controller/match.js
  matching-service/controller/matchController.js
  matching-service/database/index.js
  matching-service/index.js
  matching-service/model/index.js
  matching-service/model/matchPotential.js
  matching-service/model/matched.js
  matching-service/package-lock.json
  matching-service/package.json
  matching-service/utils/errors.js
  matching-service/utils/match.js
  testserver-service/index.js
Labels: MatchingService

#26 Update get random question endpoint
  question-service/controller/question-controller.js
  question-service/index.js
  question-service/model/db-interaction.js
  question-service/model/question-model.js
  question-service/model/question-orm.js
  question-service/test.js
Labels: QuestionService

#41 Frontend configs
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/utils/configs.js
Labels: Frontend

#44 move io.connect for matching service to matchPage, and set limit to 1…
  frontend/src/components/MatchTimer.js
  frontend/src/views/MatchingPage.js
  matching-service/.env.sample
  matching-service/config/index.js
  matching-service/index.js
Labels: bug, Frontend, priority.high

#45 Deploy UserService and Frontend
  frontend/.env.sample
  frontend/Dockerfile
  frontend/deployment.yaml
  frontend/nginx/nginx.conf
  frontend/service.yaml
  service-account.yaml
  user-service/Dockerfile
  user-service/config/config.js
  user-service/deployment.yaml
  user-service/service.yaml
Labels: Infra

#46 Deploy matching service
  frontend/Dockerfile
  frontend/deployment.yaml
  frontend/package.json
  frontend/public/index.html
  frontend/src/utils/configs.js
  frontend/src/views/MatchingPage.js
  matching-service/Dockerfile
  matching-service/config/index.js
  matching-service/deployment.yaml
  matching-service/service.yaml
Labels: Infra
