Repository CS3219-AY2223S1/cs3219-project-ay2223s1-g8, pull requests merged in 2022-11, with the labels that each got.

#118 Update README for question, user, deployment, workflows directory
  .github/workflows/README.md
  .github/workflows/scale-down-cron-job.yml
  .github/workflows/scale-up-cron-job.yml
  README.md
  deployment/README.md
  question-service/README.md
  user-service/README.md
Labels: documentation

#119 Add and standardise README for all services
  README.md
  collab-service/README.md
  collab-service/package.json
  communication-service/README.md
  frontend/.env.sample
  frontend/README.md
  frontend/package.json
  frontend/public/runtime-env.js
  frontend/src/utils/configs.js
  history-service/README.md
  matching-service/README.md
  question-service/.env.sample
  question-service/README.md
  run-services-mac.sh
  user-service/.env.sample
  user-service/README.md
Labels: documentation

#121 Delete user history when account is deleted
  frontend/public/runtime-env.js
  frontend/src/components/DeleteAccountModal/index.js
  frontend/src/middleware/historySvc.js
Labels: service.Frontend

#122 Debug cd not deploying new changes correctly
  .github/workflows/communication-cicd.yml
  .github/workflows/frontend-cicd.yml
  .github/workflows/history-cicd.yml
  .github/workflows/matching-cicd.yml
  .github/workflows/question-cicd.yml
  .github/workflows/user-cicd.yml
  user-service/index.js
Labels: bug, priority.high, Infrastructure
